#pragma once

// Enumerated type used for indexing and referencing events
enum EventName {
	RENDERER_ADD_TO_RENDERABLES,
    RENDERER_SET_CAMERA,
    RENDERER_SET_DIRECTIONAL_LIGHT,
	RENDERER_SET_AMBIENT_UP,
	RENDERER_SET_AMBIENT_DOWN,
	FIXED_UPDATE_STARTED_UPDATING_RENDERABLES,
	FIXED_UPDATE_FINISHED_UPDATING_RENDERABLES,
	SPAWN_HAZARD
};
